export const LOG_IN_REQUEST_USING_EMAIL = 'LOG_IN_REQUEST_USING_EMAIL';
export const LOG_IN_REQUEST_USING_USERNAME = 'LOG_IN_REQUEST_USING_USERNAME';
export const LOG_IN_RESPONSE = 'LOG_IN_RESPONSE';
export const LOG_USER_OUT = 'LOG_USER_OUT';
export const LOG_IN_CLEAR_PREVIOUS = 'LOG_IN_CLEAR_PREVIOUS';
