export const Afelio    	= 'https://storage.googleapis.com/ignitus/Team/afelio.jpeg'
export const Divyanshu  = 'https://storage.googleapis.com/ignitus/Team/divyanshu.jpeg'
export const Ayush    	= 'https://storage.googleapis.com/ignitus/Team/ayush.jpeg'
export const Jennifer   = 'https://storage.googleapis.com/ignitus/Team/jennifer.jpeg'
export const Paarmita   = 'https://storage.googleapis.com/ignitus/Team/paarmita.jpeg'
export const Rajvardhan = 'https://storage.googleapis.com/ignitus/Team/rajvardhan.jpeg'
export const Hafsa    	= 'https://storage.googleapis.com/ignitus/Team/Hafsa.jpeg'
export const Desire  	= 'https://storage.googleapis.com/ignitus/Team/Desire.png'

export const Avatar1    = 'https://storage.googleapis.com/ignitus/Team/avatar-bertha.png'
export const Avatar2    = 'https://storage.googleapis.com/ignitus/Team/avatar-eugene.png'
export const Avatar3    = 'https://storage.googleapis.com/ignitus/Team/avatar-george.png'
export const Avatar4    = 'https://storage.googleapis.com/ignitus/Team/avatar-grant.png'
export const Avatar5    = 'https://storage.googleapis.com/ignitus/Team/avatar-lauren.png'
export const Avatar6    = 'https://storage.googleapis.com/ignitus/Team/avatar-melanie.png'
export const Avatar7    = 'https://storage.googleapis.com/ignitus/Team/avatar-nelson.png'
export const Avatar8    = 'https://storage.googleapis.com/ignitus/Team/avatar-robert.png'