
export enum AppIcon {
  ApplyIcon = 'ApplyIcon',
  AngelListIcon = 'AngelListIcon',
  Chevron = 'Chevron',
  LinkedInIcon = 'LinkedInIcon',
  PlusIcon = 'PlusIcon',
  HeartIcon = 'HeartIcon',
  TwitterIcon = 'TwitterIcon',
  SaveIcon = 'SaveIcon',
  MessageIcon = 'MessageIcon',
  NetworkIcon = 'NetworkIcon',
	FileIcon = 'FileIcon',
	BookmarkIcon = 'BookmarkIcon',
	MapMarkerIcon = 'MapMarkerIcon',
	ChatMessageIcon = 'ChatMessageIcon',
  MentorsIcon = 'MentorsIcon',
  KeyBoardArrowDown = 'KeyBoardArrowDown',
  KeyBoardArrowRight = 'KeyBoardArrowRight',
  IgnitusFullLogo = 'IgnitusFullLogo',
}
