export const WOOTECH    = 'https://storage.googleapis.com/ignitus/partnersLogo/wootechLogo.png'
export const SUGARLABS  = 'https://storage.googleapis.com/ignitus/partnersLogo/sugarlabsLogo.png'
export const SYSTERS    = 'https://storage.googleapis.com/ignitus/partnersLogo/systersLogo.png'
export const PROGATE    = 'https://storage.googleapis.com/ignitus/partnersLogo/progateLogo.png'
export const LEANIN     = 'https://storage.googleapis.com/ignitus/partnersLogo/leanLogo.png'
export const GIRLSCRIPT = 'https://storage.googleapis.com/ignitus/partnersLogo/gsLogo.png'
