export const Avatar1    = 'https://storage.googleapis.com/ignitus/Team/avatar-bertha.png'
export const Avatar2    = 'https://storage.googleapis.com/ignitus/Team/avatar-eugene.png'
export const Avatar3    = 'https://storage.googleapis.com/ignitus/Team/avatar-george.png'
export const Avatar4    = 'https://storage.googleapis.com/ignitus/Team/avatar-grant.png'
export const Avatar5    = 'https://storage.googleapis.com/ignitus/Team/avatar-lauren.png'
export const Avatar6    = 'https://storage.googleapis.com/ignitus/Team/avatar-melanie.png'
export const Avatar7    = 'https://storage.googleapis.com/ignitus/Team/avatar-nelson.png'
export const Avatar8    = 'https://storage.googleapis.com/ignitus/Team/avatar-robert.png'